[KAN-26] CI 파이프라인 구축
watermelon-blossom/blossom-BE pull request #7
Opened 2024-06-12 05:41 UTC by JinSeoHan

closes issue [KAN-26](https://uicheon.atlassian.net/browse/KAN-26)
### 작업 분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 긴급

### 작업 개요

기존 이슈가 무엇인가(기존 이슈가 있는 경우만 작성)

- CI 파이프라인 구축했습니다.
- 테스팅을 자동화했습니다.

\* 작업 상세 내용

- 깃허브 액션을 통해 도커파일을 읽어 도커허브에 컨테이너 이미지를 push하는 CI 파이프라인을 구축했습니다.
- PR PUSH 이벤트가 발생되면 해당 코드를 빌드 및 테스트 검증할 수 있도록 깃허브 액션을 통해 자동화 했습니다.

2024-06-12 05:49 UTC, KYankee6 requested changes

2024-06-12 05:49 UTC, KYankee6 commented on .github/workflows/docker-image.yml
> +        tags: ${{ secrets.DOCKER_USERNAME }}/watermelon:latest
argoCD 경우, tag값 변화를 통해 업데이트를 가져가는 방식인데요. 혹시 태그 값을 
1. build.gradle에서 가져오거나
2. 자동으로 x.x.x <- 마지막 번째에 x+1하는 방법은 없을까요?

2024-06-12 05:51 UTC, JinSeoHan commented on .github/workflows/docker-image.yml
> +        tags: ${{ secrets.DOCKER_USERNAME }}/watermelon:latest
깃허브 액션에서 지정하는 방법이 있었던것 같아요 한번 설정해보겠습니다!

2024-06-12 06:40 UTC, JinSeoHan commented on .github/workflows/docker-image.yml
> +        tags: ${{ secrets.DOCKER_USERNAME }}/watermelon:latest
자료를 찾아보니까 태그 부분에 마지막 커밋의 고유번호를 사용하는 방법이 있더라구요 
태그 부분에 마지막 커밋 해시값을 사용하는건 어떤가요?

2024-06-12 09:34 UTC, KYankee6 commented on .github/workflows/docker-image.yml
> +        tags: ${{ secrets.DOCKER_USERNAME }}/watermelon:latest
그 방법도 괜찮을 것 같아요!

2024-06-13 14:21 UTC, KYankee6 approved these changes

2024-06-13 14:21 UTC, merged